#!/usr/bin/env bash
# Regenerate packaging/THIRD-PARTY-NOTICES.md from the module cache.
# Usage: bash scripts/gen-third-party-notices.sh [output]     (default: packaging/THIRD-PARTY-NOTICES.md)
#
# The binary a release publishes is a statically linked Go binary, which is a redistribution of every
# dependency that got linked into it. Every dependency here is permissively licensed (MIT, BSD,
# Apache-2.0), so the obligation is the notice, not the permission: ship the license text and the
# copyright line with the thing you shipped.
#
# Two rules about what goes in:
#
#   - the module set is `go list -deps ./cmd/git-pair`, not `go list -m all`. The latter lists what the
#     module graph mentions, including test-only and doc-only dependencies that never reach the binary;
#     the former lists what is linked.
#   - licence texts are deduplicated by content hash, so twenty MIT modules produce one MIT block with
#     twenty names under it, and a module that changed its licence text shows up as its own block rather
#     than hiding inside a matching name.
#
# A linked module whose cache directory carries no licence file is written into the output as an explicit
# UNLICENSED entry and makes this script exit non-zero. That is the case worth being noisy about: it
# usually means the module is not in the cache, or it licenses in a way the file names here do not cover.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=${1:-$ROOT/packaging/THIRD-PARTY-NOTICES.md}
GOMODCACHE=$(go env GOMODCACHE)

LINKED=$(go list -deps -f '{{if .Module}}{{.Module.Path}} {{.Module.Version}}{{end}}' "$ROOT/cmd/git-pair" |
  sort -u | grep -v '^gitpair ')

T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT
MISSING=0

# The module cache escapes capital letters as !x, so the directory name has to be built the same way.
cache_dir() { # cache_dir <module> <version>
  local esc
  esc=$(printf '%s' "$1" | sed 's/\([A-Z]\)/!\l\1/g')
  printf '%s/%s@%s' "$GOMODCACHE" "$esc" "$2"
}

while read -r mod ver; do
  [ -n "${mod:-}" ] || continue
  dir=$(cache_dir "$mod" "$ver")
  found=""
  for name in LICENSE LICENSE.txt LICENSE.md LICENCE COPYING NOTICE NOTICE.txt; do
    if [ -f "$dir/$name" ]; then
      found="$dir/$name"
      break
    fi
  done
  if [ -z "$found" ]; then
    printf '%s %s\n' "$mod" "$ver" >>"$T/unlicensed"
    MISSING=1
    continue
  fi
  hash=$(sha256sum "$found" | awk '{print $1}')
  printf '%s %s\n' "$mod" "$ver" >>"$T/lic-$hash.modules"
  # -f, not plain cp: the module cache is read-only, so the first copy would land as 0444 and the second
  # module sharing that licence text could not overwrite it.
  cp -f "$found" "$T/lic-$hash.text"
  notice=$(dirname "$found")/NOTICE
  if [ -f "$notice" ]; then
    cp -f "$notice" "$T/lic-$hash.notice"
  fi
done <<<"$LINKED"

{
  printf '# Third-party notices\n\n'
  printf 'Generated by `scripts/gen-third-party-notices.sh`. Do not hand-edit.\n\n'
  printf 'The `git-pair` binary is a statically linked Go binary, so it carries the following\n'
  printf 'dependencies. Each block is one distinct licence text, followed by the modules distributed\n'
  printf 'under it.\n'
  if [ -f "$T/unlicensed" ]; then
    printf '\n## No licence file found\n\n'
    printf 'These linked modules had no licence file in the module cache. Resolve before publishing.\n\n'
    sed 's/^/- /' "$T/unlicensed"
  fi
} >"$OUT"

for text in "$T"/lic-*.text; do
  [ -e "$text" ] || continue
  hash=${text##*/lic-}; hash=${hash%.text}
  {
    printf '\n---\n\n'
    printf '```\n'
    cat "$text"
    printf '```\n\n'
    printf 'Applies to:\n\n'
    sort "$T/lic-$hash.modules" | sed 's/^/- /'
  } >>"$OUT"
  if [ -f "$T/lic-$hash.notice" ]; then
    {
      printf '\n`NOTICE` carried by that module:\n\n```\n'
      cat "$T/lic-$hash.notice"
      printf '```\n'
    } >>"$OUT"
  fi
done

printf 'wrote %s (%s linked modules)\n' "$OUT" "$(printf '%s\n' "$LINKED" | grep -c . || true)"
[ "$MISSING" -eq 0 ] || {
  printf 'some linked modules carry no licence file - see the note in the output\n' >&2
  exit 1
}
